### ISSUE TITLE
Automatically move milestone from 

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr-platform#126]
Last Thursday, July 29, Joost and I had a brief discussion on the possibility of automatically creating a new milestone and moving issues to it, and how I surmised that Hugo developers might be already doing it.  The day after though, I was surprised by the following tweet:

https://twitter.com/GoHugoIO/status/1421181681717944323

> Dear `@github` moving 200+ issues from a milestone to another is a surprisingly time consuming process. /cc `@natfriedman`
 (and yes, we have been wining about this before)

So, the Hugo folks were migrating issues to new milestone manually too?  :thinking:

Anyhow, GitHub does have an Issues API that can [create a milestone](https://docs.github.com/en/rest/reference/issues#create-a-milestone) and [update an issue](https://docs.github.com/en/rest/reference/issues#update-an-issue), for example, so perhaps we can use the Issues API to accomplish what we need.

Some on-line posts even suggests the use of [GitHub CLI (`gh`)](https://cli.github.com/) to [manage milestones · Issue #1200 · cli/cli](https://github.com/cli/cli/issues/1200).

(Aside: So _that_ was what I started doing last Saturday, but veered off to looking into having `github-cli` (`gh`) packaged for Debian.)

**Comment by anthonyfok** [comment]
This is a test script that successfully move OpenDRR/opendrr-api "Sprint 39" issues to "Sprint 40" milestone.  (Tested on Thu 2021-08-05).

Note:
1. It lives on my computer as `~/bin/milestone-test.sh`
2. GitHub CLI `gh` automatically replaces `{owner}` and `{repo}` based on the Git repo directory that you are in.
3. This is _very preliminary_ and a proof of concept.  The milestones names are hardcoded.  No error checking is done whatsoever, at least not yet.  Proceed with caution!

```bash
#!/bin/bash

set -x

OLD_MILESTONE_TITLE="Sprint 39"
NEW_MILESTONE_TITLE="Sprint 40"

OLD_MILESTONE_NUMBER=$(gh api -X GET "repos/{owner}/{repo}/milestones" --jq ".[] | select(.title == \"$OLD_MILESTONE_TITLE\").number")
NEW_MILESTONE_NUMBER=$(gh api -X GET "repos/{owner}/{repo}/milestones" --jq ".[] | select(.title == \"$NEW_MILESTONE_TITLE\").number")

# Print open issues in the previous milestone 
gh api -X GET "repos/{owner}/{repo}/issues" -f milestone="$OLD_MILESTONE_NUMBER" --jq '.[] | [.number, .title, .assignee.login]'

# Move issues to the new milestone
for i in $(gh api -X GET "repos/{owner}/{repo}/issues" -f milestone="$OLD_MILESTONE_NUMBER" -f direction=asc --jq '.[].number'); do
  echo "Moving Issue $i from \"$OLD_MILESTONE_TITLE\" to \"$NEW_MILESTONE_TITLE\"..."
  gh api -X GET "repos/{owner}/{repo}/issues/$i" > "Issue-${i}-${OLD_MILESTONE_TITLE// /-}.json"
  gh api -X PATCH "repos/{owner}/{repo}/issues/$i" -f milestone="$NEW_MILESTONE_NUMBER" > "Issue-${i}-${NEW_MILESTONE_TITLE// /-}.json"
done
```

To create a milestone:

```bash
gh api -X POST repos/{owner}/{repo}/milestones -f title="Sprint 40" -f due_on=2021-08-26T15:30:00-07:00
```

* GitHub stores only the date of `due_on`, but when _creating_ a milestone with `-X POST`, it needs the whole date+time+timezone string like the above.
* No such restriction for _changing_ the `due_on` with `-X PATCH` though.  For example:

```bash
gh api -X PATCH repos/{owner}/{repo}/milestones/35 -f due_on=2021-08-05
```

TODO:

- [ ] Expand this script and turn it into something useful that our team can use.  Add features such as:
    - [ ] List all open assigned issues
    - [ ] Create new milestone with due date
- [ ] Make it cross-platform, i.e. can use on Linux, macOS and Windows.  (Implies rewriting in Python?  Or keep the bash script but provides also .bat / .ps1?)
