### ISSUE TITLE
Autobuild Docker images and push to GitHub Container registry using GitHub Actions

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr-platform#128]
In light of [Changes to Docker Hub Autobuilds](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/), our team has decided to autobuild our Docker images (`opendrr/python-env` and `opendrr/pygeoapi`) and push them to GitHub Container registry.

## Tasks

- [x] Build and push to https://ghcr.io/opendrr/pygeoapi
    - Sorry, I didn't do a PR
    - See https://github.com/OpenDRR/pygeoapi/compare/master~2...v0.10.1.gsc20211013.1 for the changes
      (see smaller incremental changes in my fork: https://github.com/anthonyfok/pygeoapi/compare/anthonyfok-ghcr-hub-tests~5...anthonyfok:anthonyfok-ghcr-hub-tests)
- [x] Build and push to https://ghcr.io/opendrr/python-env
    - [x] OpenDRR/python-env#1
    - [x] OpenDRR/python-env#2
- [x] OpenDRR/opendrr-api#133
     Update pygeoapi/Dockerfile and python/Dockerfile at https://github.com/OpenDRR/opendrr-api to use the ghcr.io registry, i.e. use  `FROM ghcr.io/opendrr/pygeoapi` and `FROM ghcr.io/opendrr/python-env`
- [ ] Document what changes I made that differ from https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/main-ci.yml and explain why
